dirs:
  temp: /nfs/production/odonovan/nmr_staging/safer_runs/1709892382
study:
  id: MTBLS1
  spectrometer.frequency: 700.0
files:
  spectral.matrix: /nfs/production/odonovan/nmr_staging/spectral_matrices/MTBLS1_1r_noesypr1d_spectralMatrix.RDS
  lib.data: /nfs/production/odonovan/nmr_staging/gissmo_ref/data.list_700MHz.RDS
corrpockets:
  half.window: 0.06
  noise.percentile: 0.99
  only.region.between: ~
  rcutoff: 0.5
storm:
  correlation.r.cutoff: 0.8
  q: 0.01
  b: 1.5
  number.of.plots: 250
tina:
  bounds:
  - -1.0
  - 11.0
  min.subset: 5.0
  prom.ratio: 0.3
  do.clustering: no
  clustering:
    max.eps: 50
    minPts: 2
    eps.stepsize: 0.01
  nfeats: 10000
  plots:
    max.plots: 600
    filtered.out: yes
    filtered.features: yes
    cleaned.clusters: yes
matching:
  cluster.profile: representative.feature
  ref.sig.SD.cutoff: 0.01
  max.hits: 5
  r.thresh: 0.8
  p.thresh: 0.01
  filtering:
    res.area.threshold: 0.25
    ppm.tol: 0.1
    max.backfits: 1E7
par:
  ncores: 24
  type: FORK
galaxy:
  enabled: no
debug:
  enabled: no
  throttle_features: 100
  all.outputs: yes
